# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
import sys, os
if hasattr(sys, 'frozen'):
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(451, 374)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(451, 374))
        MainWindow.setMaximumSize(QtCore.QSize(451, 374))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../test/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_selectimage = QtWidgets.QLineEdit(self.centralwidget)
        self.le_selectimage.setGeometry(QtCore.QRect(70, 10, 231, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_selectimage.sizePolicy().hasHeightForWidth())
        self.le_selectimage.setSizePolicy(sizePolicy)
        self.le_selectimage.setDragEnabled(False)
        self.le_selectimage.setReadOnly(True)
        self.le_selectimage.setObjectName("le_selectimage")
        self.pb_select = QtWidgets.QPushButton(self.centralwidget)
        self.pb_select.setGeometry(QtCore.QRect(310, 10, 61, 31))
        self.pb_select.setObjectName("pb_select")
        self.pb_upload = QtWidgets.QPushButton(self.centralwidget)
        self.pb_upload.setGeometry(QtCore.QRect(380, 10, 61, 31))
        self.pb_upload.setObjectName("pb_upload")
        self.le_url = QtWidgets.QLineEdit(self.centralwidget)
        self.le_url.setGeometry(QtCore.QRect(70, 50, 281, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_url.sizePolicy().hasHeightForWidth())
        self.le_url.setSizePolicy(sizePolicy)
        self.le_url.setReadOnly(True)
        self.le_url.setObjectName("le_url")
        self.le_md = QtWidgets.QLineEdit(self.centralwidget)
        self.le_md.setEnabled(True)
        self.le_md.setGeometry(QtCore.QRect(70, 90, 281, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_md.sizePolicy().hasHeightForWidth())
        self.le_md.setSizePolicy(sizePolicy)
        self.le_md.setReadOnly(True)
        self.le_md.setObjectName("le_md")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 54, 12))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 95, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_copy_url = QtWidgets.QPushButton(self.centralwidget)
        self.pb_copy_url.setGeometry(QtCore.QRect(360, 50, 81, 31))
        self.pb_copy_url.setObjectName("pb_copy_url")
        self.pb_copy_markdown = QtWidgets.QPushButton(self.centralwidget)
        self.pb_copy_markdown.setGeometry(QtCore.QRect(360, 90, 81, 31))
        self.pb_copy_markdown.setObjectName("pb_copy_markdown")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 330, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.l_preview = QtWidgets.QLabel(self.centralwidget)
        self.l_preview.setGeometry(QtCore.QRect(20, 130, 411, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_preview.sizePolicy().hasHeightForWidth())
        self.l_preview.setSizePolicy(sizePolicy)
        self.l_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_preview.setObjectName("l_preview")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 54, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片加水印上传至七牛云"))
        self.pb_select.setText(_translate("MainWindow", "Select"))
        self.pb_upload.setText(_translate("MainWindow", "upload"))
        self.label.setText(_translate("MainWindow", "URL"))
        self.label_2.setText(_translate("MainWindow", "MarkDown"))
        self.pb_copy_url.setText(_translate("MainWindow", "copy"))
        self.pb_copy_markdown.setText(_translate("MainWindow", "copy"))
        self.label_3.setText(_translate("MainWindow", "@zkalan.com"))
        self.l_preview.setText(_translate("MainWindow", "Image Preview"))
        self.label_4.setText(_translate("MainWindow", "Image"))
